
# Site settings
title: David Boureau
email: bdavidxyz@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  This is my blog. I write about front-end dev web, and acquisition.
twitter_username: bdavidxyz
github_username: bdavidxyz
linkedin_username: bdavidxyz

# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
