
# Site settings
title: David Boureau
email: bdavidxyz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog. I write about front-end dev web, and acquisition.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bdavidxyz
github_username:  bdavidxyz

# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
